version: '3' 

tasks:
  run:
    cmds:
      - uv run python -m src.app.main
    env:
      APP_HOST: 0.0.0.0
      APP_PORT: 3000
      APP_SUBPATH: /assistant
      APP_CONFIG: ./tmp/config.yaml
      STORAGES: true
      AZURE_OPENAI_API_KEY: 10bd67401d72428182716906e1de5362
  promptstudio:
    cmds:
      - uv run python -m src.app.main
    env:
      APP_HOST: 0.0.0.0
      APP_PORT: 3000
      PROMPTSTUDIO: true
      PROMPTSTUDIO_SUBPATH: /playground
      APP_CONFIG: ./tmp/config.yaml
      STORAGES: true
      APP_SUBPATH: /assistant
      AZURE_OPENAI_API_KEY: 10bd67401d72428182716906e1de5362
