nodes:
  - type: Genes
    synonyms:
      - GeneEntity
      - GeneticElement
      - DNASequence
    description: >-
      Represents a gene, which is a sequence of DNA that contains the
      information to produce a functional product, typically a protein.
    labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
    properties:
      - ensembl_id(string): Ensembl ID
      - id(string): null
      - preferred_id(string): null
      - ensembl_id(string)
      - name(string)
      - gene_id(string)
      - gene_claim_name(string)
      - gene_claim_source(string)
      - entrez_id(string)
      - symbol(string)
    outgoing_edges:
      - label: MaterialSampleToEntityAssociation
        target_vertex_labels:
          - MaterialSample
    incoming_edges:
      - label: MacromolecularMachineToCellularComponentAssociation
        source_vertex_labels:
          - CellularComponent
      - label: DrugToGeneAssociation
        source_vertex_labels:
          - Drug
      - label: MacromolecularMachineToMolecularActivityAssociation
        source_vertex_labels:
          - BiologicalProcess
      - label: PathwayGeneInteraction
        source_vertex_labels:
          - Pathway
  - type: tissue sample/sample
    synonyms:
      - BiologicalSample
      - TissueSpecimen
      - MaterialSample
    description: >-
      Represents a physical sample of biological tissue collected for analysis
      or research.
    labels:
      - Entity
      - MaterialSample
      - NamedThing
      - PhysicalEntity
    properties:
      - SMATSSCR(string): Autolysis Score
      - SMCENTER(string): Code for BSS collection site
      - SMPTHNTS(string): 'Pathology Notes, notes from PRC Report'
      - SMRIN(string): RIN Number
      - SMTS(string): >-
          Tissue Type, area from which the tissue sample was taken. This is a
          parent value to SMTSD.
      - SMTSD(string): 'Tissue Type, more specific detail of tissue type'
      - SMUBRID(string): >-
          Uberon ID, anatomical location as described by the Uber Anatomy
          Ontology (UBERON)
      - SMTSISCH(double): Total Ischemic time for a sample
      - SMTSPAX(string): Time a sample spent in the PAXgene fixative
      - SMNABTCH(string): Nucleic Acid Isolation Batch ID
      - SMNABTCHT(string): Type of nucleic acid isolation batch
      - SMNABTCHD(string): Date of nucleic acid isolation batch
      - SMGEBTCH(string): Genotype or Expression Batch ID
      - SMGEBTCHD(string): Date of genotype or expression batch
      - SMGEBTCHT(string): Type of genotype or expression batch
      - SMAFRZE(string): Samples included in the GTEx Analysis Freeze
      - SMGTC(string): Name of the genotype gtc file
      - SME2MPRT(string): >-
          End 2 Mapping Rate: Proportion of End 2 Mapped Reads to Unique
          Mapping, Vendor QC Passed Reads
      - SMCHMPRS(string): 'Chimeric Pairs: Pairs whose mates map to different genes'
      - SMNTRART(string): 'Intragenic Rate: Proportion of Intragenic Reads among Mapped Reads'
      - SMNUMGPS(string): 'Number of Gaps: Number of regions with ≥5 bases with zero coverage'
      - SMMAPRT(string): 'Mapping Rate: Proportion of Mapped Reads to Total Reads'
      - SMEXNCRT(string): 'Exonic Rate: Proportion of Exonic Reads among Mapped Reads'
      - SM550NRM(string): >-
          5' 50-based normalization:  50 (this number is the value for the
          transcript end length parameter) refers to the definition of how many
          bases are considered at the end; this value is the ratio between the
          coverage at the 5' end and the average coverage of the full
          transcript, averaged over all transcripts; 
      - SMGNSDTC(string): >-
          Genes Detected: Number of genes with at least 5 (default) High Quality
          Exonic Reads (--detection-threshold option)
      - SMUNMPRT(string): >-
          Unique Rate of Mapped: Proportion of Mapped Unique Reads to Mapped
          Reads
      - SM350NRM(string): >-
          3' 50-base normalization: the ratio between the coverage at the 3' end
          and the average coverage of the full transcript, averaged over all
          transcripts
      - SMRDLGTH(string): 'Read Length: Longest aligned length'
      - SMMNCPB(string): >-
          Mean Coverage Per Base: Coverage is averaged per base across each
          transcript, and averaged again across all transcripts.
      - SME1MMRT(string): 'End 1 Mismatch Rate: End 1 Mismatches divided by End 1 Bases'
      - SMSFLGTH(string): 'Fragment Length Std: Standard deviation of insert size'
      - SMESTLBS(string): >-
          Estimated Library Complexity: Estimated number of unique cDNA
          fragments in the library, based on Mapped Reads. The computation is
          identical to Picard's EstimateLibraryComplexity
      - SMMPPD(string): 'Mapped Reads: Unique Mapping, Vendor QC Passed Reads that were mapped'
      - SMNTERRT(string): 'Intergenic Rate: Proportion of Intergenic Reads among Mapped Reads'
      - SMRRNANM(string): >-
          rRNA: Number of all reads (duplicate and non-duplicate) aligning to
          ribosomal RNA regions
      - SMRDTTL(string): 'Total Reads: Total input reads'
      - SMVQCFL(string): >-
          Failed Vendor QC: Reads (unique) that failed platform/vendor QC (0x200
          flag)
      - SMMNCV(string): 'Mean Coverage: Mean read coverage'
      - SMTRSCPT(string): >-
          Transcripts Detected: Total number of transcripts with at least 5 exon
          mapping reads
      - SMMPPDPR(string): >-
          Total Mapped Pairs: Mapped Reads pairs that were mapped as proper
          pairs
      - SMCGLGTH(string): 'Cumulative Gap Length: Cumulative length of gap regions'
      - SMGAPPCT(string): >-
          Gap Percentage: The total cumulative gap length divided by the total
          cumulative transcript lengths
      - SMUNPDRD(string): >-
          Unpaired Reads: Unique Mapping, Vendor QC Passed Reads that were
          unpaired
      - SMNTRNRT(string): 'Intronic Rate: Proportion of Intronic Reads among Mapped Reads'
      - SMMPUNRT(string): >-
          Mapped Unique Rate of Total: Ratio of mapping of reads that were
          aligned and were not duplicates to total reads
      - SMEXPEFF(string): >-
          Expression Profiling Efficiency: Proportion of Exonic Reads among
          Unique Mapping, Vendor QC Passed Reads
      - SMMPPDUN(string): 'Mapped Unique Reads: Mapped Reads that were not duplicates'
      - SME2MMRT(string): 'End 2 Mismatch Rate: End 2 Mismatches divided by End 2 Bases'
      - SME2ANTI(string): >-
          End 2 Antisense: End 2 Mapped Reads that intersected with a anti-sense
          (-) strand feature
      - SMALTALG(string): >-
          Alternative Alignments: Reads that were mapped as secondary alignments
          (0x100 flag)
      - SME2SNSE(string): >-
          End 2 Sense: End 2 Mapped Reads that intersected with a sense (+)
          strand feature
      - SMMFLGTH(string): 'Average Fragment Length: Mean insert size'
      - SME1ANTI(string): >-
          End 1 Antisense: End 1 Mapped Reads that intersected with a anti-sense
          (-) strand feature
      - SMSPLTRD(string): 'Split Reads: The number of reads that span an exon-exon boundary'
      - SMBSMMRT(string): 'Base Mismatch Rate: Mismatched Bases divided by Total Bases'
      - SME1SNSE(string): >-
          End 1 Sense: End 1 Mapped Reads that intersected with a sense (+)
          strand feature
      - SME1PCTS(string): >-
          End 1 Sense Rate: Proportion of End 1 Sense reads among End 1 Sense
          and End 1 Antisense reads
      - SMRRNART(string): 'rRNA Rate: Proportion of rRNA Reads among Mapped Reads'
      - SME1MPRT(string): >-
          End 1 Mapping Rate: Proportion of End 1 Mapped Reads to Unique
          Mapping, Vendor QC Passed Reads
      - SMNUM5CD(string): >-
          Number Covered 5': The number of transcripts that have at least one
          read in their 5' end
      - SMDPMPRT(string): >-
          Duplicate Rate of Mapped: Proportion of Mapped Duplicate Reads to
          Mapped Reads. Complementary to Unique Rate of Mapped
      - SME2PCTS(string): >-
          End 2 Sense Rate: Proportion of End 2 Sense reads among End 2 Sense
          and End 2 Antisense reads
      - id(string): null
      - preferred_id(string): null
    outgoing_edges:
      - label: CaseToEntityAssociation
        target_vertex_labels:
          - Case
    incoming_edges:
      - label: MaterialSampleToEntityAssociation
        source_vertex_labels:
          - Gene
  - type: donor/sample donor
    synonyms:
      - Individual
      - BiologicalDonor
      - SampleProvider
    description: >-
      Represents an individual organism that provides biological samples for
      research or analysis.
    labels:
      - BiologicalEntity
      - Case
      - Entity
      - IndividualOrganism
      - NamedThing
      - OrganismalEntity
    properties:
      - sex(string): Sex of the donor
      - AGE(string): Age of the donor
      - DTHHRDY(string): Death to harvest ready time
      - id(string): null
      - preferred_id(string): null
    outgoing_edges: []
    incoming_edges:
      - label: CaseToEntityAssociation
        source_vertex_labels:
          - MaterialSample
  - type: Biological process
    synonyms:
      - BiologicalFunction
      - CellularProcess
      - MolecularProcess
    description: >-
      Represents a series of events or molecular functions that are carried out
      by living organisms to sustain life.
    labels:
      - BiologicalEntity
      - Entity
      - Gene
      - NamedThing
      - BiologicalProcess
      - BiologicalProcessOrActivity
    properties:
      - name(string): null
      - id(string): null
      - preferred_id(string): null
    outgoing_edges:
      - label: PathwayGeneInteraction
        target_vertex_labels:
          - Gene
    incoming_edges: []
  - type: cellular component
    synonyms:
      - CellPart
      - CellStructure
      - SubcellularComponent
    description: >-
      Represents a specific part or structure within a cell, such as the nucleus
      or mitochondria.
    labels:
      - AnatomicalEntity
      - BiologicalEntity
      - CellularComponent
      - Entity
      - NamedThing
      - OrganismalEntity
    properties:
      - name(string): null
      - id(string): null
      - preferred_id(string): null
    outgoing_edges:
      - label: MacromolecularMachineToCellularComponentAssociation
        target_vertex_labels:
          - Gene
    incoming_edges: []
  - type: Drug
    synonyms:
      - Medication
      - Pharmaceutical
      - ChemicalCompound
    description: >-
      Represents a chemical substance used to treat, cure, or prevent diseases
      or to enhance physical or mental well-being.
    labels:
      - ChemicalEntity
      - ChemicalMixture
      - Drug
      - Entity
      - MolecularMixture
      - NamedThing
    properties:
      - id(string): null
      - preferred_id(string): null
      - name(string)
      - concept_id(string)
      - drug_claim_name(string)
      - drug_claim_source(string)
      - drug_claim_primary_name(string)
      - drug_claim_source_db_version(string)
    outgoing_edges:
      - label: DrugToGeneAssociation
        target_vertex_labels:
          - Gene
    incoming_edges: []
  - type: molecular function or activity
    synonyms:
      - MolecularFunction
      - BiochemicalActivity
      - EnzymaticFunction
    description: >-
      Represents a specific biochemical activity or function performed by a
      molecule, such as an enzyme or protein.
    labels:
      - BiologicalEntity
      - Entity
      - NamedThing
      - BiologicalProcess
      - BiologicalProcessOrActivity
    properties:
      - name(string): null
      - id(string): null
      - preferred_id(string): null
    outgoing_edges:
      - label: MacromolecularMachineToMolecularActivityAssociation
        target_vertex_labels:
          - Gene
    incoming_edges: []
  - type: Reactome or Wiki pathway
    synonyms:
      - Pathway
      - BiologicalPathway
      - MolecularPathway
    description: >-
      Represents a series of molecular interactions or biological processes that
      lead to a specific biological outcome.
    labels:
      - BiologicalEntity
      - BiologicalProcess
      - BiologicalProcessOrActivity
      - Entity
      - NamedThing
      - Pathway
    properties:
      - name(string): null
      - id(string): null
      - preferred_id(string): null
    outgoing_edges:
      - label: PathwayGeneInteraction
        target_vertex_labels:
          - Gene
    incoming_edges: []
  - type: Clinical trial
    synonyms: [ClinicalStudy, ClinicalEntity, Study]
    description: Clinical research studies evaluating medical interventions.
    labels: [ClinicalEntity, Entity, NamedThing]
    properties:
      - id(string): Trial ID (e.g., NCT number)
      - brief_title(string)
      - official_title(string)
      - status(string)
      - brief_summary(string)
      - type(string)
      - allocation(string)
      - phases(string)
      - model(string)
      - primary_purpose(string)
      - number_of_patients(int)
      - eligibility_criteria(string)
      - healthy_volunteers(boolean)
      - sex(string)
      - minimum_age(string)
      - maximum_age(string)
      - standardised_ages(string)
      - preferred_id(string): null

  - type: Disease or Phenotypic Feature
    synonyms: [Disease, Disorder, Condition]
    labels: [BiologicalEntity, Disease, DiseaseOrPhenotypicFeature, NamedThing]
    properties:
      - keywords(string)
      - id(string)
      - preferred_id(string)
  - type: Sponsor
    synonyms: [FundingOrganization]
    labels: [AdministrativeEntity, Entity, NamedThing, Sponsor]
    properties:
      - class(string)
      - id(string)
      - preferred_id(string)
  - type: Location
    labels: [Entity, NamedThing, Location]
    properties:
      - country(string)
      - state(string)
      - city(string)
      - id(string)
      - preferred_id(string)
  - type: Outcome
    labels: [ClinicalEntity, Entity, NamedThing, Outcome]
    properties:
      - primary(boolean)
      - description(string)
      - timeframe(string)
      - id(string)
      - preferred_id(string)
  - type: Category
    labels: [Category, NamedThing]
    properties:
      - source_db(string)
      - source_db_version(string)


edges:
  - label: CaseToEntityAssociation
    properties: []
    from:
      vertex_label: MaterialSample
    to:
      vertex_label: Case
    direction: MaterialSample ➝ Case
  - label: MaterialSampleToEntityAssociation
    properties:
      - weight
      - read-counts
    from:
      vertex_label: Gene
    to:
      vertex_label: MaterialSample
    direction: Gene ➝ MaterialSample
  - label: PathwayGeneInteraction
    properties: []
    from:
      vertex_label: Pathway
    to:
      vertex_label: Gene
    direction: Pathway ➝ Gene
  - label: MacromolecularMachineToCellularComponentAssociation
    properties: []
    from:
      vertex_label: CellularComponent
    to:
      vertex_label: Gene
    direction: CellularComponent ➝ Gene
  - label: DrugToGeneAssociation
    properties:
      - score(string)
      - source(string)
      - interaction_claim_source(string)
      - interaction_type(string)
      - clinical_association(boolean)
    from:
      vertex_label: Drug
    to:
      vertex_label: Gene
    direction: Drug ➝ Gene
  - label: MacromolecularMachineToMolecularActivityAssociation
    properties: []
    from:
      vertex_label: BiologicalProcess
    to:
      vertex_label: Gene
    direction: BiologicalProcess ➝ Gene

  - label: StudyToDiseaseAssociation
    from:
      vertex_label: ClinicalEntity
    to:
      vertex_label: DiseaseOrPhenotypicFeature
    properties: []
    direction: ClinicalEntity ➝ Disease

  - label: StudyToDrugAssociation
    from:
      vertex_label: ClinicalEntity
    to:
      vertex_label: Drug
    properties:
      - description(string)
      - dose(string)
      - run_in_period(string)
    direction: ClinicalEntity ➝ Drug

  - label: StudyToLocationAssociation
    from:
      vertex_label: ClinicalEntity
    to:
      vertex_label: Location
    properties: []
    direction: ClinicalEntity ➝ Location

  - label: StudyToSponsorAssociation
    from:
      vertex_label: ClinicalEntity
    to:
      vertex_label: Sponsor
    properties: []
    direction: ClinicalEntity ➝ Sponsor

  - label: GeneHasCategory
    from:
      vertex_label: Gene
    to:
      vertex_label: Category
    properties: []
    direction: Gene ➝ Category
